name: Deployment
run-name: ${{ github.actor }} is deploying
on:
  push:
    branches:
      - master
jobs:
  Deployment:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Deploy
        env:
          SSH_HOSTNAME: ${{ secrets.SSH_HOSTNAME }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
          SSH_SECRET_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
        run: >
          mkdir .ssh &&
          echo $SSH_PUBLIC_KEY > .ssh/id_rsa.pub &&
          echo $SSH_PRIVATE_KEY > .ssh/id_rsa &&
          ssh $SSH_USERNAME@$SSH_HOSTNAME 'cd sites/makmonty.com/recipes && git pull'
