name: Deployment
run-name: ${{ github.actor }} is deploying
on:
  push:
    branches:
      - master
jobs:
  Deployment:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Deploy
        env:
          SSH_HOSTNAME: ${{ secrets.SSH_HOSTNAME }}
          SSH_USER: ${{ secrets.SSH_USERNAME }}
          SSH_SECRET_KEY: ${{ secrets.SSH_SECRET_KEY }}
        run: |
          echo $SSH_SECRET_KEY > .ssh/id_rsa
          sh -tt $SSH_USERNAME@$SSH_HOSTNAME -p $SSH_PASSWORD 'bash -s' << EOF
          cd sites/makmonty.com/recipes
          git pull
          exit
          EOF
