name: Deployment
run-name: ${{ github.actor }} is deploying
on:
  push:
    branches:
      - master
jobs:
  Deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - env:
          SSH_HOSTNAME: ${{ secrets.SSH_HOSTNAME }}
        run: echo $SSH_HOSTNAME
      - name: Deploy
        env:
          SSH_HOSTNAME: ${{ secrets.SSH_HOSTNAME }}
          SSH_USER: ${{ secrets.SSH_USERNAME }}
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        run: |
          sh -tt $SSH_USERNAME@$SSH_HOSTNAME -p $SSH_PASSWORD 'bash -s' << EOF
          cd sites/makmonty.com/recipes
          git pull
          exit
          EOF
